// Generated by CoffeeScript 2.3.1
(function() {
  /**
   * @fileoverview Tests for guard-for-in rule.
   * @author Nicholas C. Zakas
   */
  'use strict';
  var RuleTester, rule, ruleTester;

  //------------------------------------------------------------------------------
  // Requirements
  //------------------------------------------------------------------------------
  rule = require('../../rules/guard-for-in');

  ({RuleTester} = require('eslint'));

  //------------------------------------------------------------------------------
  // Tests
  //------------------------------------------------------------------------------
  ruleTester = new RuleTester({
    parser: '../../..'
  });

  ruleTester.run('guard-for-in', rule, {
    valid: ['for x of o\n  ;', 'for x of o\n  if x\n    f()', 'f() for own x of o', 'for x of o\n  if x\n    f()', 'x for x in y', 'x for x from y', 'for x of o\n  continue if x\n  f()', 'for x of o\n  if x\n    continue\n  f()'],
    invalid: [
      {
        code: 'for x of o\n  if x\n    f()\n    continue\n  g()',
        errors: [
          {
            message: 'The body of a for-of should use "own" or be wrapped in an if statement to filter unwanted properties from the prototype.',
            type: 'For'
          }
        ]
      },
      {
        code: 'for x of o\n  if x\n    continue\n    f()\n  g()',
        errors: [
          {
            message: 'The body of a for-of should use "own" or be wrapped in an if statement to filter unwanted properties from the prototype.',
            type: 'For'
          }
        ]
      },
      {
        code: 'for x of o\n  if x\n    f()\n  g()',
        errors: [
          {
            message: 'The body of a for-of should use "own" or be wrapped in an if statement to filter unwanted properties from the prototype.',
            type: 'For'
          }
        ]
      },
      {
        code: 'for x of o\n  foo()',
        errors: [
          {
            message: 'The body of a for-of should use "own" or be wrapped in an if statement to filter unwanted properties from the prototype.',
            type: 'For'
          }
        ]
      },
      {
        code: 'foo() for x of o',
        errors: [
          {
            message: 'The body of a for-of should use "own" or be wrapped in an if statement to filter unwanted properties from the prototype.',
            type: 'For'
          }
        ]
      }
    ]
  });

}).call(this);
