// Generated by CoffeeScript 2.3.1
(function() {
  /**
   * @fileoverview Rule to flag comparisons to null without a type-checking
   * operator.
   * @author Ian Christian Myers
   */
  'use strict';
  //------------------------------------------------------------------------------
  // Rule Definition
  //------------------------------------------------------------------------------
  module.exports = {
    meta: {
      docs: {
        description: 'disallow `null` comparisons without type-checking operators',
        category: 'Best Practices',
        recommended: false,
        url: 'https://eslint.org/docs/rules/no-eq-null'
      },
      schema: [],
      messages: {
        unexpected: "Use 'is'/'isnt' to compare with null."
      }
    },
    create: function(context) {
      return {
        BinaryExpression: function(node) {
          var badOperator, ref;
          badOperator = (ref = node.operator) === '==' || ref === '!=';
          if ((node.right.type === 'Literal' && node.right.raw === 'null' && badOperator) || (node.left.type === 'Literal' && node.left.raw === 'null' && badOperator)) {
            return context.report({
              node,
              messageId: 'unexpected'
            });
          }
        }
      };
    }
  };

}).call(this);
