// Generated by CoffeeScript 2.5.0
(function() {
  /**
   * @fileoverview Rule to flag statements with function invocation preceded by
   * "new" and not part of assignment
   * @author Ilya Volodin
   */
  'use strict';
  //------------------------------------------------------------------------------
  // Rule Definition
  //------------------------------------------------------------------------------
  module.exports = {
    meta: {
      type: 'suggestion',
      docs: {
        description: 'disallow `new` operators outside of assignments or comparisons',
        category: 'Best Practices',
        recommended: false,
        url: 'https://eslint.org/docs/rules/no-new'
      },
      schema: []
    },
    create: function(context) {
      return {
        'ExpressionStatement > NewExpression': function(node) {
          if (node.returns) {
            return;
          }
          return context.report({
            node: node.parent,
            message: "Do not use 'new' for side effects."
          });
        }
      };
    }
  };

}).call(this);
