// Generated by CoffeeScript 2.3.1
(function() {
  /**
   * @fileoverview Rule to flag comparisons to the value NaN
   * @author James Allardice
   */
  'use strict';
  var comparisonOpRegex;

  //------------------------------------------------------------------------------
  // Rule Definition
  //------------------------------------------------------------------------------
  comparisonOpRegex = /^[<>]=?|[!=]=|is|isnt$/;

  module.exports = {
    meta: {
      docs: {
        description: "require calls to `isNaN()` when checking for `NaN`",
        category: "Possible Errors",
        recommended: true,
        url: "https://eslint.org/docs/rules/use-isnan"
      },
      schema: []
    },
    create: function(context) {
      return {
        BinaryExpression: function(node) {
          var left, operator, right;
          ({operator, left, right} = node);
          if (comparisonOpRegex.test(operator) && (left.name === 'NaN' || right.name === 'NaN')) {
            return context.report({
              node,
              message: 'Use the isNaN function to compare with NaN.'
            });
          }
        }
      };
    }
  };

}).call(this);
