// Generated by CoffeeScript 2.5.0
// some line comment
var TerribleClass;

/**
 * this function is terrible
 * @deprecated please use 'x' instead.
 * @return null
 */
// another line comment
// with two lines
export var fn = function() {
  return null;
};

/**
 * so terrible
 * @deprecated this is awful, use NotAsBadClass.
 */
export default TerribleClass = class TerribleClass {};

/**
 * some flux action type maybe
 * @deprecated please stop sending/handling this action type.
 * @type {String}
 */
export var MY_TERRIBLE_ACTION = 'ugh';

/**
 * @deprecated this chain is awful
 * @type {String}
 */
export var CHAIN_A = 'a';

/**
 * @deprecated so awful
 * @type {String}
 */
export var CHAIN_B = 'b';

/**
 * An async function. Options requires return.
 */
export var CHAIN_C = 'C';

/**
 * this one is fine
 * @return {String} - great!
 */
export var fine = function() {
  return 'great!';
};

export var _undocumented = function() {
  return 'sneaky!';
};
